import "@/app/globals.css";
import { ContextProvider } from "@/context";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

export const metadata = {
  title: "Prime Inventory",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <ContextProvider>
          <div className='flex flex-col justify-between min-h-screen bg-gray-100 text-gray-800 w-full'>
            <div className='h-14'>
              <Navbar />
            </div>
            <div className='grow flex items-stretch justify-stretch w-full'>
              {children}
            </div>
            <Footer />
          </div>
        </ContextProvider>
      </body>
    </html>
  );
}
